### PR TITLE
Drop burst message

### PR DESCRIPTION
**Pull request by takoizumiya**
I don't need repeated message.

### CODE REVIEW

**Comment by studio3104** [comment]
Test failed...

**Comment by studio3104** [comment]
Still failed...

**Comment by takoizumiya** [comment]
hmm. Just a moment. I'll check it

**Comment by studio3104** [comment]
@takoizumiya Test has surely passed but could you check it? https://github.com/studio3104/ikasan/pull/3/files#diff-9127be19c65a1e1e34a0bf7a34a32341R44

**Comment by takoizumiya** [comment]
Yep :)
I am not familiar Ruby, but the perfect answer I want is this.
BTW, why is this correct?

**Comment by studio3104** [comment]
The reason why I said so is I hate unnecessary deeper nest
Because in this case, you expect it to do nothing if `conf[:hipchat][:restrict][:stack_burst_message]` is set `true`, right?
So I guess it's better putting `continue if conf[:hipchat][:restrict][:stack_burst_message]` first, then the unnecessary deeper nest can be removed

**Comment by takoizumiya** [comment]
Okay , got it 👍

**Pull request merged**
